services:
  web:
    build: .
    container_name: proyecto_final_TC
    # Para DESARROLLO: descomente la siguiente línea
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app   # solo en dev; quítelo en prod para imágenes inmutables
    environment:
      DJANGO_SETTINGS_MODULE: lenguaje.settings
      # Variables adicionales que su settings.py lea
      # ALLOWED_HOSTS: "jquiroz.net"
      # DEBUG: "False"
    env_file: .env
    restart: unless-stopped
    networks: [proxy-net]

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "1001:1001"          # público
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificados:/etc/nginx/certs:ro
    depends_on: [web]
    restart: unless-stopped
    networks: [proxy-net]

networks:
  proxy-net:
    driver: bridge


