version: "3.9"

services:
  web:
    build: .
    container_name: proyecto_final_TC
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DJANGO_SETTINGS_MODULE=lenguaje.settings
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "1001:1001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certificados:/etc/nginx/certs
    depends_on:
      - web

